#credencial pabx. 
EMAIL = "suporte@interativanet.com.br"
SENHA = "smk03657"

# LINHA DE TESTE (Remova depois que funcionar!)
st.write("E-mail encontrado no Secrets:", "WHATSFLUX_EMAIL" in st.secrets)

# Credenciais  do Whats
WHATSFLUX_EMAIL = "lima@interativanet.com.br"
WHATSFLUX_SENHA = "Wh@tsLima2025"

# Credenciais kanban
